In [1]:
from transformers import pipeline

[2025-08-31 00:41:41,802] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)


/home/ece/anaconda3/envs/tf-gpu-211/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/home/ece/anaconda3/envs/tf-gpu-211/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lcufile: No such file or directory
collect2: error: ld returned 1 exit status


In [1]:
import torch
from transformers import pipeline

pipe = pipeline(
    task="text-generation",
    model="Qwen/Qwen2-1.5B-Instruct",
    torch_dtype=torch.bfloat16,
    device_map=0
)

messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Tell me about the Qwen2 model family."},
]
outputs = pipe(messages, max_new_tokens=256, do_sample=True, temperature=0.7, top_k=50, top_p=0.95)
print(outputs[0]["generated_text"][-1]['content'])

[2025-08-29 18:36:10,713] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)


/home/ece/anaconda3/envs/tf-gpu-211/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/home/ece/anaconda3/envs/tf-gpu-211/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lcufile: No such file or directory
collect2: error: ld returned 1 exit status


config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Sliding Window Attention is enabled but not implemented for `sdpa`; unexpected results may be encountered.


generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0


Qwen2 is a research project by Alibaba Cloud and Baidu AI that aims to develop an advanced natural language processing (NLP) system based on the Transformer architecture, which was invented by Google in 2017.

The Qwen2 model family consists of several models, including:

  * Qwen: The first model in the series, which was released in December 2021.
  * Qwen-1B: A larger version of the Qwen model, with over one billion parameters.
  * Qwen-3B: An even larger version of the Qwen model, with over three billion parameters.

All Qwen2 models use the same Transformer architecture but are optimized for different tasks such as text generation, summarization, machine translation, and question answering.

The Qwen2 models are trained using large amounts of text data from various sources, including news articles, scientific papers, books, and social media posts. The models are designed to be highly efficient and scalable, meaning they can handle massive amounts of input data and process it quickl

In [1]:
from transformers import Qwen2Model

[2025-08-30 18:23:51,854] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)


/home/ece/anaconda3/envs/tf-gpu-211/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/home/ece/anaconda3/envs/tf-gpu-211/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lcufile: No such file or directory
collect2: error: ld returned 1 exit status


In [32]:
tokenizer.decode(tokenizer.encode("print('<|endoftext|>')<|endoftext|> he is a good boy"))

"print('<|endoftext|>')<|endoftext|> he is a good boy"

In [36]:
tokenizer.encode("he is a good boy")

[383, 374, 264, 1661, 8171]

In [8]:
len(tokenizer.vocab)

151646

In [10]:
[i for i in range(151640, 151647)]

[151640, 151641, 151642, 151643, 151644, 151645, 151646]

In [22]:
tokenizer.decode([i for i in range(151640, 151650)])

'⍨⺟⽗<|endoftext|><|im_start|><|im_end|>'

In [30]:
151646 / 32

4738.9375

In [29]:
151936 / 16

9496.0

In [16]:
2**18

262144

In [49]:
from transformers import pipeline

In [50]:
generator = pipeline('text-generation', 'Qwen/Qwen2-0.5B')

Device set to use cuda:0


In [51]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)
generator("Hello, I'm a language model", max_length=30)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Both `max_new_tokens` (=2048) and `max_length`(=30) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': "Hello, I'm a language model and I don't have the ability to create a new account or sign up for a service. However, I can provide you with some general information about how to create an account on a language model website.\n\nTo create an account on a language model website, you will need to follow these steps:\n\n1. Sign up for a free account: You can sign up for a free account on any language model website. This will allow you to access their services and test out their models.\n\n2. Create a new account: Once you have signed up for a free account, you will need to create a new account. This will involve filling out a form with your personal information and providing your payment information.\n\n3. Choose a language model: There are many language model websites available, so you will need to choose one that suits your needs. Some popular language model websites include Google Translate, Google Translate API, and Google Cloud Translation.\n\n4. Set up your accoun

In [54]:
tokens = tokenizer.encode("<|endoftext|>  Hello, I'm a language model")

In [55]:
tokens

[151643, 220, 21927, 11, 358, 2776, 264, 4128, 1614]

In [48]:
import torch
torch.tensor(tokens).unsqueeze(0).repeat(5, 1)

tensor([[9707,   11,  358, 2776,  264, 4128, 1614],
        [9707,   11,  358, 2776,  264, 4128, 1614],
        [9707,   11,  358, 2776,  264, 4128, 1614],
        [9707,   11,  358, 2776,  264, 4128, 1614],
        [9707,   11,  358, 2776,  264, 4128, 1614]])

In [58]:
from transformers import AutoTokenizer, Qwen2ForCausalLM

model = Qwen2ForCausalLM.from_pretrained("meta-qwen2/Qwen2-2-0.5b-hf")
tokenizer = AutoTokenizer.from_pretrained("meta-qwen2/Qwen2-2-0.5b-hf")

prompt = "Hey, are you conscious? Can you talk to me?"
inputs = tokenizer(prompt, return_tensors="pt")

# Generate
generate_ids = model.generate(inputs.input_ids, max_length=30)
tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]

OSError: meta-qwen2/Qwen2-2-0.5b-hf is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

In [61]:
from transformers import AutoModelForCausalLM

In [62]:
model_hf = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2-0.5B")

In [64]:
abc = model_hf.state_dict()

In [66]:
i=0
for k, v in abc.items():
    print(i)
    print(k, v.shape)
    i+=1

0
model.embed_tokens.weight torch.Size([151936, 896])
1
model.layers.0.self_attn.q_proj.weight torch.Size([896, 896])
2
model.layers.0.self_attn.q_proj.bias torch.Size([896])
3
model.layers.0.self_attn.k_proj.weight torch.Size([128, 896])
4
model.layers.0.self_attn.k_proj.bias torch.Size([128])
5
model.layers.0.self_attn.v_proj.weight torch.Size([128, 896])
6
model.layers.0.self_attn.v_proj.bias torch.Size([128])
7
model.layers.0.self_attn.o_proj.weight torch.Size([896, 896])
8
model.layers.0.mlp.gate_proj.weight torch.Size([4864, 896])
9
model.layers.0.mlp.up_proj.weight torch.Size([4864, 896])
10
model.layers.0.mlp.down_proj.weight torch.Size([896, 4864])
11
model.layers.0.input_layernorm.weight torch.Size([896])
12
model.layers.0.post_attention_layernorm.weight torch.Size([896])
13
model.layers.1.self_attn.q_proj.weight torch.Size([896, 896])
14
model.layers.1.self_attn.q_proj.bias torch.Size([896])
15
model.layers.1.self_attn.k_proj.weight torch.Size([128, 896])
16
model.layers.1.s

In [68]:
tokenizer.decode([151643, 220, 21927, 11, 358, 2776, 264, 4128, 1614])

"<|endoftext|>  Hello, I'm a language model"

In [70]:
from transformers import Qwen2Model, Qwen2Config

In [71]:
configuration = Qwen2Config()

In [72]:
configuration

Qwen2Config {
  "attention_dropout": 0.0,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 22016,
  "max_position_embeddings": 32768,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 10000.0,
  "sliding_window": 4096,
  "tie_word_embeddings": false,
  "transformers_version": "4.51.3",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

In [69]:
model

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 896)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((896,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbe

In [81]:
abc

OrderedDict([('model.embed_tokens.weight',
              tensor([[-0.0204, -0.0093,  0.0121,  ..., -0.0070,  0.0171, -0.0135],
                      [-0.0044, -0.0276,  0.0043,  ...,  0.0104,  0.0175,  0.0103],
                      [-0.0098, -0.0067,  0.0210,  ...,  0.0320,  0.0181,  0.0171],
                      ...,
                      [ 0.0099,  0.0226, -0.0137,  ..., -0.0029, -0.0280, -0.0021],
                      [ 0.0099,  0.0226, -0.0137,  ..., -0.0029, -0.0280, -0.0021],
                      [ 0.0099,  0.0226, -0.0137,  ..., -0.0029, -0.0280, -0.0021]],
                     device='cuda:0')),
             ('model.layers.0.self_attn.q_proj.weight',
              tensor([[-0.0031, -0.0155,  0.0229,  ..., -0.0079, -0.0129,  0.0025],
                      [ 0.0205,  0.0098, -0.0209,  ...,  0.0232,  0.0090, -0.0010],
                      [-0.0155, -0.0038,  0.0219,  ..., -0.0087, -0.0282,  0.0042],
                      ...,
                      [-0.0415, -0.0522, -0.0237, 

In [87]:
for k in abc.keys():
    if k=='lm_head.weight':
        print('abc')
    else:
        
        print(k)
        k = k[6:]
        print(k)
        break

model.embed_tokens.weight
embed_tokens.weight


In [75]:
abc = model.state_dict()
i=0
for k, v in abc.items():
    print(i)
    print(k, v.shape)
    i+=1

0
model.embed_tokens.weight torch.Size([151936, 896])
1
model.layers.0.self_attn.q_proj.weight torch.Size([896, 896])
2
model.layers.0.self_attn.q_proj.bias torch.Size([896])
3
model.layers.0.self_attn.k_proj.weight torch.Size([128, 896])
4
model.layers.0.self_attn.k_proj.bias torch.Size([128])
5
model.layers.0.self_attn.v_proj.weight torch.Size([128, 896])
6
model.layers.0.self_attn.v_proj.bias torch.Size([128])
7
model.layers.0.self_attn.o_proj.weight torch.Size([896, 896])
8
model.layers.0.mlp.gate_proj.weight torch.Size([4864, 896])
9
model.layers.0.mlp.up_proj.weight torch.Size([4864, 896])
10
model.layers.0.mlp.down_proj.weight torch.Size([896, 4864])
11
model.layers.0.input_layernorm.weight torch.Size([896])
12
model.layers.0.post_attention_layernorm.weight torch.Size([896])
13
model.layers.1.self_attn.q_proj.weight torch.Size([896, 896])
14
model.layers.1.self_attn.q_proj.bias torch.Size([896])
15
model.layers.1.self_attn.k_proj.weight torch.Size([128, 896])
16
model.layers.1.s

In [80]:
model.model.norm.weight

Parameter containing:
tensor([ 7.5625,  8.0000,  7.2188,  7.3125,  7.4688,  7.3750,  6.0000,  7.1875,
         7.5312,  6.9688,  7.6250,  7.5312,  7.3438,  6.7812,  6.4375,  7.2188,
         9.7500,  7.3750,  7.2500,  7.5625,  8.5000,  7.3438,  7.6250,  9.9375,
         6.4062,  8.8750,  7.4375,  6.6875,  7.2500,  7.6875,  6.9062,  7.5938,
         7.5312,  7.5312,  7.3438,  7.3438,  7.2812,  7.4375,  7.1875,  7.7812,
         9.3125,  6.7500,  7.1562,  6.8750,  7.5312,  7.5938,  7.5312,  7.1562,
         7.5625,  7.3438,  7.5000,  7.5312,  6.9062,  7.4062,  7.5625,  7.5312,
         6.6250,  7.6250,  7.2188,  7.7500,  7.4062, 10.6875,  7.4062,  7.5000,
        10.7500,  7.0000,  7.5000,  6.2812,  7.3750,  7.3750,  7.3125,  7.5625,
         7.1250,  7.2812,  7.0625,  7.3438,  7.4375,  6.8750,  9.5625,  7.4375,
         7.4375,  7.8750,  6.9062,  7.5000,  7.5000,  7.2500,  6.9375,  7.0938,
         7.0625,  7.3438,  7.4688,  7.4375,  7.3125,  9.0625,  7.4062,  7.5625,
         7.6250,  

In [ ]:
model.lm_head.weight

Parameter containing:
tensor([[-0.0204, -0.0093,  0.0121,  ..., -0.0070,  0.0171, -0.0135],
        [-0.0044, -0.0276,  0.0043,  ...,  0.0104,  0.0175,  0.0103],
        [-0.0098, -0.0067,  0.0210,  ...,  0.0320,  0.0181,  0.0171],
        ...,
        [ 0.0099,  0.0226, -0.0137,  ..., -0.0029, -0.0280, -0.0021],
        [ 0.0099,  0.0226, -0.0137,  ..., -0.0029, -0.0280, -0.0021],
        [ 0.0099,  0.0226, -0.0137,  ..., -0.0029, -0.0280, -0.0021]],
       device='cuda:0', requires_grad=True)

In [78]:
model.model.embed_tokens.weight

Parameter containing:
tensor([[-0.0204, -0.0093,  0.0121,  ..., -0.0070,  0.0171, -0.0135],
        [-0.0044, -0.0276,  0.0043,  ...,  0.0104,  0.0175,  0.0103],
        [-0.0098, -0.0067,  0.0210,  ...,  0.0320,  0.0181,  0.0171],
        ...,
        [ 0.0099,  0.0226, -0.0137,  ..., -0.0029, -0.0280, -0.0021],
        [ 0.0099,  0.0226, -0.0137,  ..., -0.0029, -0.0280, -0.0021],
        [ 0.0099,  0.0226, -0.0137,  ..., -0.0029, -0.0280, -0.0021]],
       device='cuda:0', requires_grad=True)

In [88]:
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2-0.5B")
model.state_dict()

OrderedDict([('model.embed_tokens.weight',
              tensor([[-0.0204, -0.0093,  0.0121,  ..., -0.0070,  0.0171, -0.0135],
                      [-0.0044, -0.0276,  0.0043,  ...,  0.0104,  0.0175,  0.0103],
                      [-0.0098, -0.0067,  0.0210,  ...,  0.0320,  0.0181,  0.0171],
                      ...,
                      [ 0.0099,  0.0226, -0.0137,  ..., -0.0029, -0.0280, -0.0021],
                      [ 0.0099,  0.0226, -0.0137,  ..., -0.0029, -0.0280, -0.0021],
                      [ 0.0099,  0.0226, -0.0137,  ..., -0.0029, -0.0280, -0.0021]])),
             ('model.layers.0.self_attn.q_proj.weight',
              tensor([[-0.0031, -0.0155,  0.0229,  ..., -0.0079, -0.0129,  0.0025],
                      [ 0.0205,  0.0098, -0.0209,  ...,  0.0232,  0.0090, -0.0010],
                      [-0.0155, -0.0038,  0.0219,  ..., -0.0087, -0.0282,  0.0042],
                      ...,
                      [-0.0415, -0.0522, -0.0237,  ...,  0.0425, -0.0374,  0.0065],
    

In [4]:
from transformers import AutoTokenizer
import torch
tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen2-0.5B', trust_remote_code=True)
tokens = tokenizer.encode(" Hello, I'm a language model")
tokens = torch.tensor(tokens, dtype=torch.long).unsqueeze(0).repeat(1, 1)
tokens

tensor([[21927,    11,   358,  2776,   264,  4128,  1614]])

In [6]:
import torch
from torch.nn import functional as F
from transformers import AutoModelForCausalLM

# model = Qwen2Model.from_pretrained('Qwen/Qwen2-0.5B')
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2-0.5B")
model.eval()
model.to('cuda')
torch.manual_seed(52)
torch.cuda.manual_seed(52)
tokens = [21927,    11,   358,  2776,   264,  4128,  1614]# "Hello, I'm a language model,"
tokens = torch.tensor(tokens, dtype=torch.long) # (8,)
tokens = tokens.unsqueeze(0).repeat(5, 1) # (5, 8)
x = tokens.to('cuda')

# generate!
while x.size(1) < 30: # max_length=30
    # forward the model to get the logits
    with torch.no_grad():
        logits = model(x)[0] # (B, T, vocab_size)
        # take the logits at the last position
        logits = logits[:, -1, :] # (B, vocab_size)
        # get the probabilities
        probs = F.softmax(logits, dim=-1)
        # do top-k sampling of 50 (huggingface pipeline default)
        # topk_probs here becomes (5, 50), topk_indices is (5, 50)
        topk_probs, topk_indices = torch.topk(probs, 50, dim=-1)
        # select a token from the top-k probabilities
        # note: multinomial does not demand the input to sum to 1
        ix = torch.multinomial(topk_probs, 1) # (B, 1)
        # gather the corresponding indices
        xcol = torch.gather(topk_indices, -1, ix) # (B, 1)
        # append to the sequence
        x = torch.cat((x, xcol), dim=1)

# print the generated text
# import tiktoken
# enc = tiktoken.get_encoding('gpt2')
for i in range(5):
    tokens = x[i, :30].tolist()
    decoded = tokenizer.decode(tokens)
    print(">", decoded)

Sliding Window Attention is enabled but not implemented for `sdpa`; unexpected results may be encountered.


>  Hello, I'm a language model and I can help you with your English translation. I can translate between different languages such as Russian, Spanish, Portuguese
>  Hello, I'm a language model for solving problems and answering questions, especially about linguistics and how to pronounce different languages well. Based on my training
>  Hello, I'm a language model!
Sure, what would you like to know?
That's just great. I can certainly assist you in any way
>  Hello, I'm a language model for my text generation capabilities and have a question about the topic "how to improve the language model." Can you help
>  Hello, I'm a language model AI so I can't take advice.
But if I have a lot of work to do, at 10


In [94]:
model

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 896)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((896,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbe

In [97]:
2**15

32768

In [99]:
from transformers import Qwen2RMSNorm

ImportError: cannot import name 'Qwen2RMSNorm' from 'transformers' (/home/ece/anaconda3/envs/tf-gpu-211/lib/python3.10/site-packages/transformers/__init__.py)